# Generated by Django 5.2.4 on 2025-10-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (USD, NGN, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='flutterwave_response',
            field=models.JSONField(blank=True, help_text='Full response from Flutterwave', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used (card, bank transfer, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Flutterwave transaction ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(help_text='Transaction reference from Flutterwave', max_length=100, unique=True),
        ),
    ]
