# Generated by Django 5.2.4 on 2025-10-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_payment_options_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_number',
            field=models.IntegerField(default=1),
        ),
    ]
